### ISSUE TITLE
Python code to find factorial of a number

### ISSUE THREAD

**Issue by Sachindrck** [Sachindrck/hactoberfest_contribution_2022#11]
The factorial of a number is the product of all the integers from 1 to that number.

For example, the factorial of 6 is 1x2x3x4x5x6 = 720. Factorial is not defined for negative numbers, and the factorial of zero is one, 0! = 1.

**Comment by sid-rajput** [comment]
@Sachindrck  assign it to me

**Comment by Sachindrck** [comment]
@sid-rajput go ahead

**Comment by Sachindrck** [comment]
#32
