### ISSUE TITLE
add merge sort in c++

### ISSUE THREAD

**Issue by panka17** [Sachindrck/hactoberfest_contribution_2022#119]
I want to add merge sort algorithm in c++. Please assign it to me @Sachindrck

**Comment by Sachindrck** [comment]
@deja-v you can do bubble, count, or other sorts

**Comment by deja-v** [comment]
@Sachindrck okay I will do it. Can you assign them

**Comment by Sachindrck** [comment]
@deja-v okay

**Comment by Sachindrck** [comment]
#137
