### ISSUE TITLE
Python Program to Solve Quadratic Equation

### ISSUE THREAD

**Issue by Sachindrck** [Sachindrck/hactoberfest_contribution_2022#12]
The standard form of a quadratic equation is:

ax2 + bx + c = 0, where
a, b and c are real numbers and
a ≠ 0

The solutions to this quadratic equation are given by:

(-b ± (b ** 2 - 4 * a * c) ** 0.5) / (2 * a)

**Comment by anshu-6537** [comment]
Can you assign this issue to me !!

**Comment by Sachindrck** [comment]
@anshu-6537 assigned.

**Comment by Swapnil05Rai** [comment]
can you assign this to me !!

**Comment by Sachindrck** [comment]
@Swapnil05Rai already assigned, you can work on some other issues or add new issues if you have any.

**Comment by Sachindrck** [comment]
#62
