### ISSUE TITLE
C++ program for converting decimal number to binary number

### ISSUE THREAD

**Issue by Mikhiel39** [Sachindrck/hactoberfest_contribution_2022#127]
->Technical issue
->I want to add a project in c++ using friend function (OOP) for converting decimal number to binary number . Here you can enter any decimal number and can get a binary number of the respective decimal number. I will a provide cpp file with the code and output of the code in it. 
->I have intermediate level skills in c++ (OOP).
->It will take me one day to finish and upload this project.

**Comment by Sachindrck** [comment]
@Mikhiel39 Go ahead, do it!

**Comment by Sachindrck** [comment]
#164
