### ISSUE TITLE
C++ program for 0 1 Knapsack Problem

### ISSUE THREAD

**Issue by aditi072** [Sachindrck/hactoberfest_contribution_2022#129]
I want to contribute 0-1 knapsack problem in C++ . Please assign it to me @Sachindrck

**Comment by 87abdul** [comment]
I'm new to this program and i want to contribute . It will be very helpful if you could  assign to me this problem.
@Sachindrck

**Comment by code-genier** [comment]
@Sachindrck, can you please assign this problem to me? This would be my first contribution to open source

**Comment by 23SumiTM** [comment]
I Want To Contribute  To This Problem.

**Comment by Sachindrck** [comment]
@87abdul @code-genier @23SumiTM you can check other issues.

**Comment by Sachindrck** [comment]
#174
