### ISSUE TITLE
Python Program to Convert Celsius To Fahrenheit

### ISSUE THREAD

**Issue by Sachindrck** [Sachindrck/hactoberfest_contribution_2022#13]
In the program below, we take a temperature in degree Celsius and convert it into degree Fahrenheit. They are related by the formula:

fahrenheit = celsius * 1.8 + 32

**Comment by anshu-6537** [comment]
Can you assign this issue to me !!

**Comment by Sachindrck** [comment]
@anshu-6537 assigned.
