### ISSUE TITLE
Python Program to Check if a Number is Odd or Even

### ISSUE THREAD

**Issue by Sachindrck** [Sachindrck/hactoberfest_contribution_2022#14]
A number is even if it is perfectly divisible by 2. When the number is divided by 2, we use the remainder operator % to compute the remainder. If the remainder is not zero, the number is odd.

**Comment by likun-3993** [comment]
please assign me this task

**Comment by Sachindrck** [comment]
@likun-3993 do it!

**Comment by Sachindrck** [comment]
https://github.com/Sachindrck/hactoberfest_contribution_2022/pull/30
