### ISSUE TITLE
Python Program to Check Armstrong Number

### ISSUE THREAD

**Issue by Sachindrck** [Sachindrck/hactoberfest_contribution_2022#15]
A positive integer is called an Armstrong number of order n if

abcd... = a^n + b^n + c^n + d^n + ...
In the case of an Armstrong number of 3 digits, the sum of cubes of each digit is equal to the number itself. For example:

153 = 1*1*1 + 5*5*5 + 3*3*3  // 153 is an Armstrong number.

**Comment by coder-mohan** [comment]
hey @Sachindrck please assign it to me . I'll do it

**Comment by Sachindrck** [comment]
@coder-mohan go ahead, do it!

**Comment by coder-mohan** [comment]
@Sachindrck I have done it with code and also written algorithm . can you please merge with hacktoberfest label.

**Comment by Sachindrck** [comment]
#29
