### ISSUE TITLE
Program for Tower of Hanoi Algorithm

### ISSUE THREAD

**Issue by Sachindrck** [Sachindrck/hactoberfest_contribution_2022#157]
Tower of Hanoi is a mathematical puzzle where we have three rods (A, B, and C) and N disks. Initially, all the disks are stacked in decreasing value of diameter i.e., the smallest disk is placed on the top and they are on rod A. The objective of the puzzle is to move the entire stack to another rod (here considered C), obeying the following simple rules: 

Only one disk can be moved at a time.
Each move consists of taking the upper disk from one of the stacks and placing it on top of another stack i.e. a disk can only be moved if it is the uppermost disk on a stack.
No disk may be placed on top of a smaller disk.

**Comment by 87abdul** [comment]
Could please assign this problem to me @Sachindrck ?

**Comment by 87abdul** [comment]
I have added Tower of Hanoi  program  with comment .Thanks

**Comment by 87abdul** [comment]
I have added Tower of Hanoi program with comment .Thanks @Sachindrck

**Comment by Sachindrck** [comment]
#163
