### ISSUE TITLE
Write a Program in Python to Count Uppercase, Lowercase, special character and numeric values 

### ISSUE THREAD

**Issue by Sachindrck** [Sachindrck/hactoberfest_contribution_2022#159]
Given a string, write a program to count the occurrence of Lowercase characters, Uppercase characters, Special characters, and Numeric values.

**Comment by rahulsingh522003** [comment]
Please assign this task to me @Sachindrck

**Comment by rahulsingh522003** [comment]
Hey @Sachindrck 
I have completed this task.  Can you please check and merge it with Hacktoberfest-accept label.
#187

**Comment by Sachindrck** [comment]
#187
