### ISSUE TITLE
Program to find Smallest and Largest Word in a String

### ISSUE THREAD

**Issue by Sachindrck** [Sachindrck/hactoberfest_contribution_2022#161]
Given a string, find the minimum and the maximum length words in it. 

Examples: 

Input: "This is a test string"
Output: Minimum length word: a
         Maximum length word: string

**Comment by RajatRathore123-github** [comment]
I would like to do this . @Sachindrck  Please assign me this issue

**Comment by Sachindrck** [comment]
#192
