### ISSUE TITLE
Python "Hello, World!" Program

### ISSUE THREAD

**Issue by Sachindrck** [Sachindrck/hactoberfest_contribution_2022#21]

**Comment by ajjayymahato** [comment]
Please assign this issue to me.

**Comment by ajjayymahato** [comment]
Please review this PR and also assign label hactoberfest-accepted to this issue. PR #41

**Comment by Sachindrck** [comment]
#41

**Comment by Sachindrck** [comment]
Accepted the PR, it is automatically accepted for hacktoberfest.
