### ISSUE TITLE
C++ Program for Rock, Paper, and Scissors Game

### ISSUE THREAD

**Issue by Sachindrck** [Sachindrck/hactoberfest_contribution_2022#23]
This is a simple to demonstrate rock, paper, scissors game. In this game, players have to choose one of the three options to beat the opponent.

**Comment by likun-3993** [comment]
does the work flow go like this  :  
player one chooses then the second player then we display a win or loss...simple as that ??

**Comment by Sachindrck** [comment]
@likun-3993 yes

**Comment by likun-3993** [comment]
can you assign me this task please?

**Comment by Pensuveze** [comment]
please assign it to me its an request

**Comment by anshu-6537** [comment]
Can we make the computer as the opponent and the user plays against it ..??
please assign this program to me ..!!!

**Comment by Sachindrck** [comment]
@anshu-6537 yes, we can give an option in starting to choose where to play against any friend or against the computer.

**Comment by Sachindrck** [comment]
#77
