### ISSUE TITLE
Difference between sums of odd and even digits

### ISSUE THREAD

**Issue by Sachindrck** [Sachindrck/hactoberfest_contribution_2022#270]
Given a long integer, we need to find if the difference between sum of odd digits and sum of even digits is 0 or not. The indexes start from zero (0 index is for leftmost digit).
Examples: 
 

Input : 1212112
Output : Yes
Explanation:-
the odd position element is 2+2+1=5
the even position element is 1+1+1+2=5
the difference is 5-5=0.so print yes.

Input :12345
Output : No
Explanation:-
the odd position element is 1+3+5=9
the even position element is 2+4=6
the difference is 9-6=3 not  equal
to zero. So print no.

**Comment by sourav-gt47** [comment]
sir , can i solve this ?

**Comment by sourav-gt47** [comment]
@Sachindrck

**Comment by Sachindrck** [comment]
#282
