### ISSUE TITLE
Java Program to Find Largest Element of an Array

### ISSUE THREAD

**Issue by Sachindrck** [Sachindrck/hactoberfest_contribution_2022#52]
In this program, you'll learn to find the largest element in an array using a for loop in Java.

**Comment by destroyer5067** [comment]
@Sachindrck  can you assign this issue to me?

**Comment by Priyanshi-Rai** [comment]
> In this program, you'll learn to find the largest element in an array using a for loop in Java.

Please assign this task to me ;)
