### ISSUE TITLE
Java Program to Find Transpose of a Matrix

### ISSUE THREAD

**Issue by Sachindrck** [Sachindrck/hactoberfest_contribution_2022#54]
Transpose of a matrix is the process of swapping the rows to columns. For the 2x3 matrix,

Matrix
a11    a12    a13
a21    a22    a23

Transposed Matrix
a11    a21
a12    a22
a13    a23

**Comment by TurboPug2101** [comment]
HI,please assign mei this issue.

**Comment by Sachindrck** [comment]
@TurboPug2101 go ahead 👍

**Comment by Sachindrck** [comment]
#59
