### ISSUE TITLE
Python Program to Extract Extension From the File Name

### ISSUE THREAD

**Issue by Sachindrck** [Sachindrck/hactoberfest_contribution_2022#72]

**Comment by Mikasa-Ackerman2074** [comment]
Hey @Sachindrck  can you assign this issue to me, i am good with python

**Comment by ujjwalpathaak** [comment]
Hello, @Sachindrck I recently started learning python at my college and I think this would be great to start contributing to open source and for my python practice as well.
Can you please assign it to me?

**Comment by Sachindrck** [comment]
@ujjwalpathaak go ahead, do it.

**Comment by Sachindrck** [comment]
@Mikasa-Ackerman2074 please check other issues.

**Comment by Sachindrck** [comment]
#109
